name = "sveltekit-edge-og-image"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-07-18"

wasm_modules = { resvg = "./node_modules/@resvg/resvg-wasm/index_bg.wasm" }

# workers_dev = true

# [build]
# command = "CF_PAGES=1 npm run build"

# Bind your static output directory (e.g. the client folder SvelteKit emitted)
[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
